---
abstract: 'dead easy benchmarking'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attribute-Benchmark
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Attribute::Benchmark:
    file: lib/Attribute/Benchmark.pm
    version: 0.001
requires:
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Attribute-Benchmark/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Attribute-Benchmark
  homepage: https://metacpan.org/release/Attribute-Benchmark
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-attribute-benchmark
version: 0.001
